main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Home url
    path('', views.home, name='home'),
    # About url
    path('about/', views.about, name='about'),
    # auth urls
    path('accounts/signup/', views.signup, name='signup'),
    
    # Course urls
    path('courses/', views.CourseList.as_view(), name='courses_index'),
    path('courses/<int:course_id>/', views.CourseDetail.as_view(), name='courses_detail'),
    path('courses/add_course/', views.CourseCreate.as_view(), name='courses_create'),
    path('courses/<int:pk>/update', views.CourseUpdate.as_view(), name='courses_update'),
    path('courses/<int:pk>/delete', views.CourseDelete.as_view(), name='courses_delete'),
    path('courses/<int:course_id>/join/', views.join_course, name='join_course'),
    path('courses/<int:course_id>/leave/', views.leave_course, name='leave_course'),
    path('courses/owned/', views.owned_courses, name='owned_courses'),
    path('courses/enrolled/', views.enrolled_courses, name='enrolled_courses'),

    # Post Views
    path('posts/', views.PostList.as_view(), name='posts_index'),
    path('posts/<int:post_id>/', views.posts_detail, name='posts_detail'),
    path('posts/create/', views.PostCreate.as_view(), name='posts_create'),
    path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='posts_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='posts_delete'),
    path('posts/<int:course_id>/add_post/', views.add_post, name='add_post'),
    # Comment Views
    path('posts/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    # Assignment Views
    path('assignments/<int:pk>/', views.AssignmentDetail.as_view(), name='assignments_detail'),
    path('assignments/create/', views.AssignmentCreate.as_view(), name='assignments_create'),
    path('assignments/<int:pk>/update/', views.AssignmentUpdate.as_view(), name='assignments_update'),
    path('assignments/<int:pk>/delete/', views.AssignmentDelete.as_view(), name='assignments_delete'),
    path('assignments/<int:course_id>/add_assignment/', views.add_assignment, name='add_assignment'),
    # Submission Views
    path('assignments/<int:assignment_id>/add_submission/', views.upload_submission, name='upload_submission'),
    path('assignments/<int:assignment_id>/submissions/<int:submission_id>/', views.submission_detail, name='submission_detail'),
]

teacheasy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import AbstractUser


SUBJECTS = (
    ('SCI', 'Science'),
    ('HIS', 'History'),
    ('SOC', 'Social Studies'),
    ('MATH', 'Mathematics'),
    ('ENG', 'English'),
    ('CS', 'Computer Science'),
    ('ART', 'Arts')
)


# Create your models here.

class User(AbstractUser):
    pass

class DaysOfTheWeek(models.Model):
    day = models.CharField(max_length=10)
    
    def __str__(self):
        return self.day


class Course(models.Model):
    name = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()
    # to facilitate schedules being multiple days of the week we utilized a separate object to store dates with a many to many relationship between classes and days
    days = models.ManyToManyField(DaysOfTheWeek)
    subject = models.CharField(max_length=4, choices=SUBJECTS, default=SUBJECTS[0][0])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    students = models.ManyToManyField(User, related_name='courses_enrolled', blank=True)


    def __str__(self):
        return f'Course {self.name}, {self.start_date}-{self.end_date}'
    
    def get_absolute_url(self):
        return reverse('courses_detail', kwargs={'course_id': self.id})


class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=500)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Post {self.title} from course {self.course}'
    
# comments model
class Comment(models.Model):
    body = models.CharField(max_length=500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Comment {self.body} on post {self.post}'

# assignments
class Assignment(models.Model):
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=500)
    due_date = models.DateField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Assignment {self.title} for course {self.course}'

# submissions

class Submission(models.Model):
    url = models.CharField(max_length=200)
    comment = models.CharField(max_length=1000)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Submission file {self.url} for assignment {self.assignment}'

main_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Comment, Post, Assignment, Course

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body',)

class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ('title', 'body', 'due_date',)


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ('name', 'start_date', 'end_date', 'days', 'subject',)       

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'password')

main_app/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from main_app.models import Course, Post, Comment, Assignment, Submission
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm, CourseForm, PostForm, AssignmentForm, RegisterForm
import uuid, boto3, os
User = get_user_model

# Create your views here.

# Home view
def home(request):
    return render(request, 'home.html')

# About view
def about(request):
    return render(request, 'about.html')

# Sign Up View

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = RegisterForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'

  form = RegisterForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

# Course Views
class CourseList(ListView):
    model = Course
    template_name = 'courses/index.html'
    context_object_name = 'courses'

    def get_queryset(self):
        return Course.objects.all()

class CourseDetail(DetailView):
    model = Course
    template_name = 'courses/detail.html'
    pk_url_kwarg = 'course_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_in_course'] = self.object.students.filter(id=self.request.user.id).exists()
        return context

class CourseUpdate(LoginRequiredMixin, UpdateView):
    model = Course
    template_name = 'courses/update.html'     
    fields = '__all__'

class CourseDelete(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = 'courses/delete.html'
    success_url = '/courses'

class CourseCreate(LoginRequiredMixin, CreateView):
    model = Course
    fields = ['name', 'start_date', 'end_date', 'days', 'subject']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

@login_required
def owned_courses(request):
    user = request.user
    owned_courses = Course.objects.filter(user=user)

    context = {
        'owned_courses': owned_courses,
    }

    return render(request, 'courses/owned_courses.html', context)
    

@login_required
def enrolled_courses(request):
    user = request.user
    enrolled_courses = user.course_set.all() 

    context = {
        'enrolled_courses': enrolled_courses,
    }

    return render(request, 'courses/enrolled_courses.html', context)

@login_required
def join_course(request, course_id):
    Course.objects.get(id=course_id).students.add(request.user)

    return redirect('courses_detail', course_id=course_id)

@login_required
def leave_course(request, course_id):
    Course.objects.get(id=course_id).students.remove(request.user)

    return redirect('courses_detail', course_id=course_id)

# Post Views
class PostList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/index.html'

@login_required
def posts_detail(request, post_id):
    return render(request, 'posts/detail.html', {
        'post': Post.objects.get(id=post_id),
        'comment_form': CommentForm()
    })

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = '__all__'

    def form_valid(self, form):
        return super().form_valid(form)

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = '__all__'

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts'

@login_required
def add_post(request, course_id):
    form = PostForm(request.POST)

    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.course_id = course_id
        new_post.user_id = request.user.id
        new_post.save()

    return redirect('courses_detail', course_id=course_id)

# Comment Views

@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.post_id = post_id
        new_comment.user_id = request.user.id
        new_comment.save()

    return redirect('posts_detail', post_id=post_id)

def delete_comment(request, post_id, comment_id):
    Comment.objects.get(id=comment_id).delete()
    return redirect('posts_detail', post_id=post_id)


# Assignment Views

class AssignmentDetail(LoginRequiredMixin, DetailView):
    model = Assignment
    template_name = 'assignments/detail.html'

class AssignmentCreate(LoginRequiredMixin, CreateView):
    model = Assignment
    fields = '__all__'

    def form_valid(self, form):
        return super().form_valid(form)

class AssignmentUpdate(LoginRequiredMixin, UpdateView):
    model = Assignment
    fields = '__all__'

class AssignmentDelete(LoginRequiredMixin, DeleteView):
    model = Assignment
    success_url = '/assignments'

@login_required
def add_assignment(request, course_id):
    form = AssignmentForm(request.POST)

    if form.is_valid():
        new_assignment = form.save(commit=False)
        new_assignment.course_id = course_id
        new_assignment.user_id = request.user.id
        new_assignment.save()

    return redirect('courses_detail', course_id=course_id)    

# Submission Views

@login_required
def submission_detail(request, assignment_id, submission_id):
    return render(request, 'submissions/detail.html', {
        'assignment': Assignment.objects.get(id=assignment_id),
        'submission': Submission.objects.get(id=submission_id)
    })

@login_required
def upload_submission(request, assignment_id):
    submission_file = request.FILES.get('submission-file', None)
    if submission_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + submission_file.name[submission_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(submission_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Submission.objects.create(url=url, assignment_id=assignment_id, user=request.user, comment=request.POST.get('comment', ' '))
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
            print(os.environ['S3_BUCKET'])
    return redirect('assignments_detail', pk=assignment_id)

main_app/templates/courses/delete.html
{% extends 'base.html' %}
<div class="container-fluid">
  <div class="row content">
        <div class="col-sm-10 dashboard">
            <br>
            <h2>Course View</h2>
            <br>
            {% block content %}
            <h1>Confirm Deletion</h1>
            <p>Are you sure you want to delete this course?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit">Confirm Delete</button>
            </form>
            <a href="{% url 'courses_index' %}">Cancel</a>
        </div>
  </div>
</div>
{% endblock %}

main_app/templates/courses/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/courses.css' %}">
{% endblock %}
{% block content %}

    <h1 class="header">Course Details</h1>

    <div class="card">
        <div class="card-content">
            <h3 class="card-title">{{ course.name }}</h3>
        </div>
        <div class="card-action">
            {% if request.user == course.user %} {# Check if the current user is the owner #}
            <div class="teacher-buttons">  
                <a href="{% url 'courses_update' course.id %}">Edit</a>
                <a href="{% url 'courses_delete' course.id %}">Delete</a>
            </div>      
            {% endif %}
            {% if not user_in_course %}
            <form class="button" method="post" action="{% url 'join_course' course.id %}">
                {% csrf_token %}
                <button type="submit">Join Course</button>
            </form>
            {% else %}
            <form class="button" method="post" action="{% url 'leave_course' course.id %}">
                {% csrf_token %}
                <button type="submit">Leave Course</button>
            </form>
            {% endif %}
        </div>
    </div>
    <div class="course-content">
        <div class="assignment-list">
            <h2>Current Assignments</h2>
            {% if request.user == course.user %} {# Check if the current user is the owner #}
            <div class="card">
                <form action="{% url 'add_assignment' course.id %}" method="POST" class="card-body">
                    {% csrf_token %}
                    <input type="text" name="title" class="form-control assignemnt-title" placeholder="Title here">
                    <br>
                    <textarea name="body" class="form-control assignment" placeholder="showcase your writing skills here" rows="5" maxlength="500"></textarea>
                    <br>
                    <input type="date" name="due_date" class="form-control assignment">
                    <br>
                    <input type="submit" value="Add Assignment" class="btn btn-success add-assignment-btn">
                </form>
            </div> 
            {% endif %}   
            {% for assignment in course.assignment_set.all %}
            <div class="card post"  style="width: 18rem;">
                <a href="{% url 'assignments_detail' assignment.id %}" class="navlinks">
                    <div class="card-body">
                        <h3 class="card-text poster-name"><small>{{assignment.title}}</small></h3>
                    </div>
                </a>    
            </div>
            {% endfor %} 
        </div>
        <div class="post-list">
            <h2>Posts</h2>
            {% if request.user == course.user %}
            <div class="card">
                <form action="{% url 'add_post' course.id %}" method="POST" class="card-body">
                    {% csrf_token %}
                    <input type="text" name="title" class="form-control post" placeholder="Title here">
                    <br>
                    <textarea name="body" class="form-control post" placeholder="showcase your writing skills here" rows="5" maxlength="500"></textarea>
                    <br>
                    <input type="submit" value="Add Post" class="btn btn-success add-post-btn">
                </form>
            </div> 
            {% endif %}
            {% for post in course.post_set.all %}
                <div class="card post" style="width: 18rem;">
                    <a href="{% url 'posts_detail' post.id %}" class="navlinks">
                        <div class="card-body">
                            <h5 class="card-title">{{post.title}}</h5>
                        </div>
                    </a>   
                </div>
            {% endfor %}
        </div>
    </div>    
{% endblock %}

main_app/templates/courses/enrolled_courses.html
{% extends 'base.html' %}
{% block content %}
    <h1>Your Enrolled Courses</h1>
    <ul>
        {% for course in enrolled_courses %}
            <li><a href="{% url 'courses_detail' course.id %}">{{ course.name }}</a></li>
        {% empty %}
            <li>You are not enrolled in any courses.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'courses_index' %}">Back to Courses</a>
{% endblock %}

main_app/templates/courses/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/posts.css' %}">
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row content">
      <div class="post-list">
          <br>
          <h2 class="flex-head">All Courses</h2>
          <br>  
          {% for course in courses %}
          <div class="card">
              <a href="{% url 'courses_detail' course.id %}">
                  <div class="card-body">
                      <h3 class="card-title poster-name">{{ course.name }}</h3>
                      <h3 class="post-title">{{ course.user }}</h3>
                    </div>
                </a>
            </div>
            {% endfor %}
            <a href="{% url 'courses_create' %}" class="flex-head">Create a Course</a>
        </div>
  </div>
</div>
{% endblock %}

main_app/templates/courses/owned_courses.html
{% extends 'base.html' %}
{% block content %}
    <h1>Your Owned Courses</h1>
    <ul>
        {% for course in owned_courses %}
            <li><a href="{% url 'courses_detail' course.id %}">{{ course.name }}</a></li>
        {% empty %}
            <a>You don't own any courses yet.</a>
        {% endfor %}
    </ul>
    <a href="{% url 'home' %}">Back to Dashboard</a>
    <a href="{% url 'courses_create' %}">Create a Course</a>
{% endblock %}

main_app/templates/courses/update.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-10 dashboard">
      <br>
      <h2>Edit Course</h2>
      <br>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
      </form>
      <a href="{% url 'courses_index' %}">Back to Courses</a>
    </div>
  </div>
</div>
{% endblock %}